

kind: Deployment
apiVersion: apps/v1
metadata:
  name: ollama
  namespace: prakashm88-dev
  labels:
    app: ollama
    app.kubernetes.io/component: ollama
    app.kubernetes.io/instance: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ollama
        app.kubernetes.io/component: ollama
        app.kubernetes.io/instance: ollama
    spec:
      volumes:
        - name: volume-data
          emptyDir: {}
#        - name: ollama-storage
#          persistentVolumeClaim:
#            claimName: ollama-storage
      containers:
        - resources:
            limits:
              cpu: '2'
              memory: 6Gi
            requests:
              cpu: '2'
              memory: 6Gi
          terminationMessagePath: /dev/termination-log
          name: container
          env:
            - name: OLLAMA_ORIGINS
              value: '*'
            - name: CUDA_VISIBLE_DEVICES
              value: '0'
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: volume-data
              mountPath: /.ollama
#            - name: ollama-storage
#              mountPath: /.ollama
          terminationMessagePolicy: File
          image: 'docker.io/ollama/ollama:0.5.3-rc0'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600 